### ISSUE TITLE
Make Data Hub accessible

### ISSUE THREAD

**Issue by 5annaha** [OdysseusLarp/odysseus-social-hub#5]
Make Data Hub accessible:

- [x] Change background color from gradient to one color (the dark one)
- [x] Increase Ship Log font size
- [x] Change Chat Contacts color. Now the color is too shiny (hard to read)
- [x] Add font size selection for the chat (small, medium, large)

Use this tool to find better colors and font sizes:
[https://snook.ca/technical/colour_contrast/colour.html#fg=02F6FE,bg=333333](https://snook.ca/technical/colour_contrast/colour.html#fg=02F6FE,bg=333333)

**Comment by nicou** [comment]
Completed
